### PR TITLE
fix issue https://github.com/ThemeFuse/Unyson/issues/1610

### PR DESCRIPTION
**Pull request by player0k**

### CODE REVIEW

**Comment by moldcraft** [comment]
Thank you!

**Comment by danyj** [comment]
@player0k  , @moldcraft  Tested , same thing , 
here is video 
http://take.ms/lCp8F

**Comment by player0k** [comment]
There are two different tables... another table hasn't price row, button row options as result no value for rows which was specific as "default row"

**Comment by danyj** [comment]
@player0k  I understand that but if you setup a pricing table and by mistake switch , everything is gone and you must sett it up again.

**Comment by player0k** [comment]
@danyj  I have no solution to this problem

**Comment by player0k** [comment]
@danyj , Actually if you are not press to save after change table. You can get old values if you change row positions back to previous values
http://screencast.com/t/HlGSJpzr9i

**Comment by danyj** [comment]
aaa, so switching the sides works, ok that would do it than

**Pull request merged**
